name: NextJS Docker CI CD for China Mainland

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo 📦
              uses: actions/checkout@v4
            - name: Build Docker Image 🐳
              run: |
                  docker build -t i-manual.chitubox.com .
            - name: Check Docker Images 🥽
              run: |
                  docker images
                  docker save i-manual.chitubox.com -o i-manual.chitubox.com.tar
                  chmod go+rw i-manual.chitubox.com.tar
                  ls -l
            - name: Transfer Image tar File to Server 🚢
              uses: appleboy/scp-action@master
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ vars.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ vars.PORT }}
                  source: i-manual.chitubox.com.tar
                  target: /var/www/html/
            - name: Load the Docker Image and Run Container 🚀
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ vars.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ vars.PORT }}
                  script: |
                      docker stop c-manual.chitubox.com
                      docker rm c-manual.chitubox.com
                      docker rmi i-manual.chitubox.com
                      cd /var/www/html/
                      docker load -i i-manual.chitubox.com.tar
                      rm i-manual.chitubox.com.tar
                      docker run --name c-manual.chitubox.com -p 3000:3000 -d i-manual.chitubox.com
