name: NextJS Docker CI CD for China Mainland

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Build Docker Image and Run Container 🚀
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/bitnami/projects/manual.chitubox.com
                      git pull origin main
                      sudo docker stop c-manual.chitubox.com
                      sudo docker rm c-manual.chitubox.com
                      sudo docker rmi i-manual.chitubox.com
                      sudo docker build -t i-manual.chitubox.com .
                      sudo docker images
                      sudo docker run --name c-manual.chitubox.com -p 3003:3000 -d i-manual.chitubox.com
