name: NextJS Docker CI CD for China Mainland

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo 📦
              uses: actions/checkout@v4
            - name: Build Docker Image 🐳
              run: |
                  docker build --build-arg NEXT_PUBLIC_ORAMA_ENDPOINT="$NEXT_PUBLIC_ORAMA_ENDPOINT" --build-arg NEXT_PUBLIC_ORAMA_API_KEY="$NEXT_PUBLIC_ORAMA_API_KEY" -t i-docs.chitubox.com .
              env:
                  NEXT_PUBLIC_ORAMA_ENDPOINT: ${{ vars.NEXT_PUBLIC_ORAMA_ENDPOINT }}
                  NEXT_PUBLIC_ORAMA_API_KEY: ${{ vars.NEXT_PUBLIC_ORAMA_API_KEY }}
            - name: Check Docker Images 🥽
              run: |
                  docker images
                  docker save i-docs.chitubox.com -o i-docs.chitubox.com.tar
                  chmod go+rw i-docs.chitubox.com.tar
                  ls -l
            - name: Transfer Image tar File to Server 🚢
              uses: appleboy/scp-action@master
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ vars.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ vars.PORT }}
                  source: i-docs.chitubox.com.tar
                  target: /var/www/html/
            - name: Load the Docker Image and Run Container 🚀
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ vars.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ vars.PORT }}
                  script: |
                      docker stop c-docs.chitubox.com
                      docker rm c-docs.chitubox.com
                      docker rmi i-docs.chitubox.com
                      cd /var/www/html/
                      docker load -i i-docs.chitubox.com.tar
                      rm i-docs.chitubox.com.tar
                      docker run --name c-docs.chitubox.com -p 3000:3000 -d i-docs.chitubox.com
