name: NextJS Static CI CD

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [lts/*]
                # See supported Node.js release at https://github.com/actions/setup-node

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Use pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build:export
            - name: Compress build
              run: |
                  zip -r out.zip out
                  ls -l
            - name: Transfer zip file to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  source: out.zip
                  target: /var/www/html/manual.chitubox.com/
            - name: Unzip file on server
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ vars.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.PRIVATE_KEY }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /var/www/html/manual.chitubox.com/
                      unzip out.zip
                      rm out.zip
